---
language: generic
jobs:
  include:
    - env: [ omnilint ]
      install: docker pull lpenz/omnilint
      script: docker run --rm -v "$PWD:$PWD" -e "RWD=$PWD" -e "MY_UID=$UID" lpenz/omnilint
    - env: [ cmake ]
      script:
        - mkdir _build _install
        - cd _build
        - cmake -DCMAKE_INSTALL_PREFIX=../_install ..
        - make VERBOSE=1
        - make install
        - cd ../_install
        - find . -type f
