---
language: generic
install: docker pull debian:stretch
script:
  - docker run -d --name debian -v "$PWD/..":/home debian:stretch sleep 9999999999
  - docker exec -t debian /bin/bash -c "apt-get update && apt-get install -y --no-install-recommends git-buildpackage fakeroot build-essential debhelper"
  - docker exec -t debian /bin/bash -c "cd /home/urxvt-ext-notify-osc && gbp buildpackage --git-ignore-branch -us -uc"
  - docker rm -f debian
  - sudo chown -R "$USER:$USER" ../
  - ls -l ..
