---
name: CI
on: [ workflow_dispatch, push, pull_request ]
jobs:
  omnilint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: docker://lpenz/omnilint:0.5.2
  tests:
    strategy:
        matrix:
          preset:
            - install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: docker://lpenz/ghaction-cmake:0.23.0
        with:
          preset: ${{ matrix.preset }}
  publish-packagecloud:
    needs: [ omnilint, tests ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant:
          - image: debian-bookworm-amd64
            distro: debian
            version: bookworm
          - image: debian-trixie-amd64
            distro: debian
            version: trixie
          - image: ubuntu-noble-amd64
            distro: ubuntu
            version: noble
          - image: raspbian-bookworm-armhf
            distro: raspbian
            version: bookworm
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
      - uses: docker/setup-qemu-action@v3.6.0
      - uses: docker://lpenz/ghaction-cmake:0.23.0
        if: matrix.variant.image == 'debian-bookworm-amd64'
        with:
          preset: cpack
      - uses: docker://lpenz/ghaction-cmake:0.23.0
        if: matrix.variant.image == 'debian-trixie-amd64'
        with:
          preset: cpack
      - uses: docker://lpenz/ghaction-cmake:0.23.0
        if: matrix.variant.image == 'ubuntu-noble-amd64'
        with:
          preset: cpack
      - uses: docker://lpenz/ghaction-cmake:0.23.0
        if: matrix.variant.image == 'raspbian-bookworm-armhf'
        with:
          preset: cpack
      - run: |
          for f in *.deb; do ls -l "$f"; dpkg --info "$f"; done
      - id: version
        uses: docker://lpenz/ghaction-version-gen:0.14.1
      - uses: docker://lpenz/ghaction-packagecloud:0.4
        if: steps.version.outputs.version_commit != ''
        with:
          repository: ${{ matrix.variant.distro }}/${{ matrix.variant.distro }}/${{ matrix.variant.version }}
        env:
          PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
