---
name: CI
on: [ workflow_dispatch, push, pull_request ]
jobs:
  omnilint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: docker://lpenz/omnilint:0.5
  tests:
    strategy:
        matrix:
          preset:
            - install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: docker://lpenz/ghaction-cmake:0.21.0
        with:
          preset: ${{ matrix.preset }}
  packagecloud:
    needs: [ omnilint, tests ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0
      - uses: docker://lpenz/ghaction-cmake:0.21.0
        with:
          preset: cpack
      - run: |
          dpkg --info *.deb
          dpkg --contents *.deb
      - uses: docker://lpenz/ghaction-packagecloud:0.4
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          repository: debian/debian/bullseye
        env:
          PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}

