---
name: CI
on: [ push, pull_request ]
jobs:
  tests:
    strategy:
        matrix:
          preset:
            - install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker://lpenz/ghaction-cmake:v0.12
        with:
          preset: ${{ matrix.preset }}
  omnilint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker://lpenz/omnilint:v0.2
  packagecloud:
    needs: [ omnilint, tests ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: docker://lpenz/ghaction-cmake:v0.12
        with:
          preset: cpack
      - run: |
          dpkg --info *.deb
          dpkg --contents *.deb
      - uses: docker://lpenz/ghaction-packagecloud:v0.3
        if: github.ref == 'refs/heads/main'
        with:
          repository: debian/debian/buster
        env:
          PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}

