---
name: CI
on: [ workflow_dispatch, push, pull_request ]
jobs:
  omnilint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: docker://lpenz/omnilint:0.5.1
  tests:
    strategy:
        matrix:
          preset:
            - cpack
            - install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - uses: docker://lpenz/ghaction-cmake:0.22.0
        with:
          preset: ${{ matrix.preset }}
  publish-packagecloud:
    needs: [ omnilint, tests ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant:
          - image: debian-bullseye-amd64
            distro: debian
            version: bullseye
          - image: debian-bookworm-amd64
            distro: debian
            version: bookworm
          - image: ubuntu-jammy-amd64
            distro: ubuntu
            version: jammy
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - uses: docker/setup-qemu-action@v3.0.0
      - uses: docker://lpenz/ghaction-cmake:0.22.0-debian-bullseye-amd64
        if: matrix.variant.image == 'debian-bullseye-amd64'
        with:
          preset: cpack
      - uses: docker://lpenz/ghaction-cmake:0.22.0-debian-bookworm-amd64
        if: matrix.variant.image == 'debian-bookworm-amd64'
        with:
          preset: cpack
      - uses: docker://lpenz/ghaction-cmake:0.22.0-ubuntu-jammy-amd64
        if: matrix.variant.image == 'ubuntu-jammy-amd64'
        with:
          preset: cpack
      - run: |
          for f in *.deb; do ls -l "$f"; dpkg --info "$f"; done
      - id: version
        uses: docker://lpenz/ghaction-version-gen:0.13.5
      - uses: docker://lpenz/ghaction-packagecloud:0.4
        if: steps.version.outputs.version_commit != ''
        with:
          repository: ${{ matrix.variant.distro }}/${{ matrix.variant.distro }}/${{ matrix.variant.version }}
        env:
          PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}

